
    create table public.airline (
       code varchar(255) not null,
        token varchar(255) not null,
        date_created timestamp,
        last_updated timestamp,
        cancelled boolean not null,
        description varchar(255),
        primary key (code, token)
    )

    create table public.announce (
       id integer generated by default as identity,
        date_created timestamp,
        last_updated timestamp,
        token varchar(255) not null,
        announce_type varchar(10),
        arrival varchar(255) not null,
        cancelled boolean not null,
        departure varchar(255) not null,
        end_date date not null,
        price decimal(19,2) not null,
        start_date date not null,
        status varchar(10),
        weight decimal(19,2) not null,
        airline_code varchar(255),
        airline_token varchar(255),
        primary key (id)
    )

    create table public.auth_user (
       id integer not null,
        date_created timestamp,
        last_updated timestamp,
        username varchar(15) not null,
        token varchar(255) not null,
        cancelled boolean not null,
        password varchar(255) not null,
        remember_me boolean not null,
        user_user_id varchar(15),
        user_token varchar(255),
        primary key (id)
    )

    create table public.message (
       id integer not null,
        token varchar(255) not null,
        date_created timestamp,
        last_updated timestamp,
        cancelled boolean not null,
        content varchar(255),
        r_announce_id integer,
        primary key (id, token)
    )

    create table public.prod_category (
       code varchar(255) not null,
        token varchar(255) not null,
        date_created timestamp,
        last_updated timestamp,
        cancelled boolean not null,
        description varchar(255),
        primary key (code, token)
    )

    create table public.user (
       user_id varchar(15) not null,
        token varchar(255) not null,
        date_created timestamp,
        last_updated timestamp,
        cancelled boolean not null,
        email varchar(255),
        first_name varchar(255),
        gender integer,
        last_name varchar(255),
        phone varchar(255),
        primary key (user_id, token)
    )
create sequence hibernate_sequence start with 1 increment by 1

    alter table public.announce 
       add constraint FKpe188e759kviy8is0gt6gr532 
       foreign key (airline_code, airline_token) 
       references public.airline

    alter table public.auth_user 
       add constraint FK6wp4nfq1f57e13ejryo6w0q8j 
       foreign key (user_user_id, user_token) 
       references public.user

    alter table public.message 
       add constraint FKmphjqe8onn2djytekd7e9gms9 
       foreign key (r_announce_id) 
       references public.announce
