--INITIALISATION TABLE CATEGORY

INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('ELECTRONIQUE','Electronique');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('VETEMENTS','Vetements');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('BIJOUX','Bijoux');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('DOCUMENTS','Documents');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('AUTRES','Autres');



--INITIALISATION TABLE ROLE
INSERT INTO ROLE(ID,DESCRIPTION) VALUES (1,'ADMIN');
INSERT INTO ROLE(ID,DESCRIPTION) VALUES (2,'USER');





--MySQL

INSERT INTO category (CODE, DESCRIPTION) VALUES ('ELECTRONIQUE','Electronique');
INSERT INTO category (CODE, DESCRIPTION) VALUES ('VETEMENTS','Vetements');
INSERT INTO category (CODE, DESCRIPTION) VALUES ('BIJOUX','Bijoux');
INSERT INTO category (CODE, DESCRIPTION) VALUES ('DOCUMENTS','Documents');
INSERT INTO category (CODE, DESCRIPTION) VALUES ('AUTRES','Autres');



INSERT INTO role(ID,DESCRIPTION) VALUES (1,'ADMIN');
INSERT INTO role(ID,DESCRIPTION) VALUES (2,'USER');