--INITIALISATION TABLE ROLE
INSERT INTO ROLE(ID,DESCRIPTION) VALUES (1,'ADMIN');
INSERT INTO ROLE(ID,DESCRIPTION) VALUES (2,'USER');



-- TABLE DE JOINTURE
INSERT INTO USER_ROLE(R_USER,ROLE_ID) VALUES (1,1);

INSERT INTO ANNOUNCE_CATEGORY(ANNOUNCE_ID,CATEGORIES_CODE) VALUES (1,'VETEMENTS');
INSERT INTO ANNOUNCE_CATEGORY(ANNOUNCE_ID,CATEGORIES_CODE) VALUES (2,'VETEMENTS');
INSERT INTO ANNOUNCE_CATEGORY(ANNOUNCE_ID,CATEGORIES_CODE) VALUES (3,'VETEMENTS');




INSERT INTO PUBLIC.AIRLINE (CODE, TOKEN, DATECREATED, LASTUPDATED, CANCELLED, DESCRIPTION) VALUES ('AIRFRANCE', 'PM', '2020-10-04 23:06:55.398000', '2020-10-04 23:06:55.398000', false, 'AIR FRANCE');

COMMIT;