--INITIALISATION TABLE CATEGORY

INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('ELECTRONIQUE','Electronique');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('VETEMENTS','Vetements');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('BIJOUX','Bijoux');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('DOCUMENTS','Documents');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('-','-');



--INITIALISATION TABLE ROLE
INSERT INTO ROLE(ID,DESCRIPTION) VALUES (1,'ADMIN');
INSERT INTO ROLE(ID,DESCRIPTION) VALUES (2,'USER');