INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('ELECTRONIQUE','Electronique');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('VETEMENTS','Vetements');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('BIJOUX','Bijoux');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('DOCUMENTS','Documents');
INSERT INTO PUBLIC.CATEGORY (CODE, DESCRIPTION) VALUES ('-','-');
