--INITIALISATION TABLE ROLE

INSERT INTO ROLE(ID,DESCRIPTION) VALUES (1,'ROLE_ADMIN');
INSERT INTO ROLE(ID,DESCRIPTION) VALUES (2,'ROLE_USER');

--INITIALISATION TABLE UTILISATEURS
--admin@admadminin.com/admin
--demo/password2
--demo1/password3
INSERT INTO USER(ID, USERNAME, PASSWORD,ACTIVE,CANCELLED,EMAIL,FIRST_NAME,LAST_NAME) values (1,  'admin@admin.com', '$2a$10$ISnv6T5sqpr5YeRKP01xEOLAr/ZWviCp73BC07hMK54GNgQHMemxm', 1,false , 'admin@admin.com','admin','nistrateur');
INSERT INTO USER(ID, USERNAME, PASSWORD,ACTIVE,CANCELLED,EMAIL,FIRST_NAME,LAST_NAME) values (2,  'demo', '$2a$10$5TLZBQgB/FOSkccGjKCRDerrD6YzsFznyNURwNHZG8tEwAumfFw1C', 1,false,'demo@admin.com','demo','tration');
INSERT INTO USER(ID, USERNAME, PASSWORD, ACTIVE,CANCELLED,EMAIL,FIRST_NAME,LAST_NAME) values (3, 'demo1', '$2a$10$U2NARRA6lp0CSfDF2JEmtOaAbf3bVGx9zGqDbLkW/T59.QdGnlguO', 0,true,'demo1@admin.com','denmo1','tration');--inactif user



-- TABLE DE JOINTURE
INSERT INTO USER_ROLE(R_USER,ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLE(R_USER,ROLE_ID) VALUES (1,2);
INSERT INTO USER_ROLE(R_USER,ROLE_ID) VALUES (2,2);
INSERT INTO USER_ROLE(R_USER,ROLE_ID) VALUES (3,2);

COMMIT;