INSERT INTO PUBLIC.PROD_CATEGORY (CODE, DESCRIPTION) VALUES ('ELECTRO','Electronique');
INSERT INTO PUBLIC.PROD_CATEGORY (CODE, DESCRIPTION) VALUES ('VETEMENT','Vetements');
INSERT INTO PUBLIC.PROD_CATEGORY (CODE, DESCRIPTION) VALUES ('BIJOUX','Bijoux');
INSERT INTO PUBLIC.PROD_CATEGORY (CODE, DESCRIPTION) VALUES ('DOCUMENTS','Documents');
