INSERT INTO PUBLIC.PROD_CATEGORY (CODE, TOKEN, DATECREATED, LASTUPDATED, CANCELLED, DESCRIPTION) VALUES ('ELECTRO', 'PM', current_timestamp(), current_timestamp(), 0, 'Electronique');
INSERT INTO PUBLIC.PROD_CATEGORY (CODE, TOKEN, DATECREATED, LASTUPDATED, CANCELLED, DESCRIPTION) VALUES ('VETEMENT', 'PM', current_timestamp(), current_timestamp(), 0, 'Vetements');
INSERT INTO PUBLIC.PROD_CATEGORY (CODE, TOKEN, DATECREATED, LASTUPDATED, CANCELLED, DESCRIPTION) VALUES ('BIJOUX', 'PM', current_timestamp(), current_timestamp(), 0, 'Bijoux');
INSERT INTO PUBLIC.PROD_CATEGORY (CODE, TOKEN, DATECREATED, LASTUPDATED, CANCELLED, DESCRIPTION) VALUES ('DOCUMENTS', 'PM', current_timestamp(), current_timestamp(), 0, 'Documents');
