-- we don't know how to generate database MANAGER (class Database) :(
create table ADMINISTRATOR
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EF0266FA_C342_4493_9809_8666A956CE0C) auto_increment
        primary key,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    EMAIL VARCHAR(255) not null,
    NAME VARCHAR(255) not null,
    USERNAME VARCHAR(255) not null,
    CANCELLED BOOLEAN not null
);

create table AIRLINE
(
    CODE VARCHAR(255) not null,
    TOKEN VARCHAR(255) not null,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    CANCELLED BOOLEAN not null,
    DESCRIPTION VARCHAR(255),
    primary key (CODE, TOKEN)
);

create table BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AC69676B_0698_4323_ABC9_936E8C7DB810) auto_increment
        primary key,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) not null,
    JOB_KEY VARCHAR(32) not null,
    unique (JOB_NAME, JOB_KEY)
);

create table BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D84D3E64_780B_4D4F_BCB0_93C81C64C8E9) auto_increment
        primary key,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT not null,
    CREATE_TIME TIMESTAMP(26,6) not null,
    START_TIME TIMESTAMP(26,6) default NULL,
    END_TIME TIMESTAMP(26,6) default NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP(26,6),
    JOB_CONFIGURATION_LOCATION VARCHAR(2500),
    constraint JOB_INST_EXEC_FK
        foreign key (JOB_INSTANCE_ID) references BATCH_JOB_INSTANCE
);

create table BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID BIGINT not null
        primary key,
    SHORT_CONTEXT VARCHAR(2500) not null,
    SERIALIZED_CONTEXT VARCHAR,
    constraint JOB_EXEC_CTX_FK
        foreign key (JOB_EXECUTION_ID) references BATCH_JOB_EXECUTION
);

create table BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID BIGINT not null,
    TYPE_CD VARCHAR(6) not null,
    KEY_NAME VARCHAR(100) not null,
    STRING_VAL VARCHAR(250),
    DATE_VAL TIMESTAMP(26,6) default NULL,
    LONG_VAL BIGINT,
    DOUBLE_VAL DOUBLE,
    IDENTIFYING CHAR(1) not null,
    constraint JOB_EXEC_PARAMS_FK
        foreign key (JOB_EXECUTION_ID) references BATCH_JOB_EXECUTION
);

create table BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E2573F64_A9FD_4164_9E05_10633EEDCB8F) auto_increment
        primary key,
    VERSION BIGINT not null,
    STEP_NAME VARCHAR(100) not null,
    JOB_EXECUTION_ID BIGINT not null,
    START_TIME TIMESTAMP(26,6) not null,
    END_TIME TIMESTAMP(26,6) default NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP(26,6),
    constraint JOB_EXEC_STEP_FK
        foreign key (JOB_EXECUTION_ID) references BATCH_JOB_EXECUTION
);

create table BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID BIGINT not null
        primary key,
    SHORT_CONTEXT VARCHAR(2500) not null,
    SERIALIZED_CONTEXT VARCHAR,
    constraint STEP_EXEC_CTX_FK
        foreign key (STEP_EXECUTION_ID) references BATCH_STEP_EXECUTION
);

create table CATEGORY
(
    CODE VARCHAR(15) not null
        primary key,
    DESCRIPTION VARCHAR(255) not null
);

create table COMMUNICATION
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3C5998A7_49D7_4521_A10A_BA2B27FD6116) auto_increment
        primary key,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    CONTENT VARCHAR(255) not null,
    TYPE VARCHAR(255) not null,
    R_ADMIN_ID BIGINT,
    CANCELLED BOOLEAN not null,
    constraint FKH9HRBGRAKSHF04DBAUJ1IYWEL
        foreign key (R_ADMIN_ID) references ADMINISTRATOR
);

create table CONTACT_US
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_19C5997B_704A_4947_B860_D4C38AA08087) auto_increment
        primary key,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    CONTENT VARCHAR(500) not null,
    RECEIVER VARCHAR(255) not null,
    SENDER VARCHAR(255) not null,
    SUBJECT VARCHAR(255) not null,
    PSEUDO_SENDER VARCHAR(255)
);

create table IMAGE
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_05F5A143_E1BE_4B09_89E7_B653C9B9DC16) auto_increment
        primary key,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    NAME VARCHAR(255) not null
        unique,
    TYPE VARCHAR(255),
    ORIGIN VARCHAR(255),
    PIC_BYTE binary
);

create table NOTIFICATION
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4C0C169B_FD14_40FE_87B7_31A8A97D07B3) auto_increment
        primary key,
    CANCELLED BOOLEAN not null,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    R_ANNOUNCE_ID BIGINT,
    MESSAGE VARCHAR(255) not null,
    R_USER_ID BIGINT,
    SESSION_ID VARCHAR(255),
    STATUS VARCHAR(10) not null,
    TITLE VARCHAR(60) not null,
    TYPE VARCHAR(10) not null,
    USER_ID BIGINT not null
);

create table ROLE
(
    ID INTEGER default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1FED53EF_8B5F_4E3B_8284_362944C442BD) auto_increment
        primary key,
    DESCRIPTION VARCHAR(255) not null
);

create table USER
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E4F4FA1D_134C_496F_B2C3_918226591F6C) auto_increment
        primary key,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    ACTIVE INTEGER not null,
    CANCELLED BOOLEAN not null,
    CONFIRM_TOKEN VARCHAR(255),
    EMAIL VARCHAR(255) not null
        unique,
    FACEBOOK_ID VARCHAR(255),
    FIRST_NAME VARCHAR(255) not null,
    GENDER VARCHAR(10),
    GOOGLE_ID VARCHAR(255),
    LAST_NAME VARCHAR(255) not null,
    PASSWORD VARCHAR(255) not null,
    PHONE VARCHAR(35) not null,
    USERNAME VARCHAR(15) not null
        unique,
    IMAGE_ID BIGINT,
    ENABLE_NOTIF BOOLEAN not null ,
    ERROR VARCHAR(255),
    unique (EMAIL, USERNAME),
    constraint FKPKUUKDHP1VI4PQWEMNYGTNO1T
        foreign key (IMAGE_ID) references IMAGE
);

create table ANNOUNCE
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_91928703_951F_4D3A_AE18_11A34EF0B7CF) auto_increment
        primary key,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    TOKEN VARCHAR(255) not null,
    ANNOUNCE_TYPE VARCHAR(10),
    ARRIVAL VARCHAR(255) not null,
    CANCELLED BOOLEAN not null,
    DEPARTURE VARCHAR(255) not null,
    DESCRIPTION VARCHAR(255) not null,
    END_DATE TIMESTAMP(26,6) not null,
    GOLD_PRICE DECIMAL(19,2) not null,
    PRENIUM_PRICE DECIMAL(19,2) not null,
    PRICE DECIMAL(19,2) not null,
    START_DATE TIMESTAMP(26,6) not null,
    STATUS VARCHAR(10),
    TRANSPORT VARCHAR(255) not null,
    WEIGHT DECIMAL(19,2) not null,
    R_USER_ID BIGINT,
    REMAIN_WEIGHT DECIMAL(19,2),
    IMAGE_ID BIGINT,
    COUNTRESERVATION INTEGER,
    constraint FKFW0TKPEM5N1S5HA75UD6QJMQ
        foreign key (R_USER_ID) references USER,
    constraint FKP72D81HLBK413NI11Y1D57RHQ
        foreign key (IMAGE_ID) references IMAGE
);

create unique index PRIMARY_KEY_B9
    on ANNOUNCE (ID);

create table ANNOUNCE_CATEGORY
(
    ANNOUNCE_ID BIGINT not null,
    CATEGORIES_CODE VARCHAR(15) not null,
    primary key (ANNOUNCE_ID, CATEGORIES_CODE),
    constraint FKDLW4JG18D18NXMEQB8AHFXRWF
        foreign key (ANNOUNCE_ID) references ANNOUNCE,
    constraint FKQ084C7R4NIQ9HTWTJS3XQSQFF
        foreign key (CATEGORIES_CODE) references CATEGORY
);

create table MESSAGE
(
    ID BIGINT not null,
    TOKEN VARCHAR(255) not null,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    CANCELLED BOOLEAN not null,
    CONTENT VARCHAR(255),
    R_ANNOUNCE BIGINT,
    R_USER_ID BIGINT,
    USERNAME VARCHAR(255),
    primary key (ID, TOKEN),
    constraint FKE39G9PLVG5K7X0GDURX5IIDLK
        foreign key (R_ANNOUNCE) references ANNOUNCE,
    constraint FKOGVI3LF5JH16WQIAXRRPJSXMA
        foreign key (R_USER_ID) references USER
);

create table RESERVATION
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E6583612_CCF1_41BF_91A5_2676CB0DFADA) auto_increment
        primary key,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    WEIGTH DECIMAL(19,2) not null,
    R_ANNOUNCE_ID BIGINT,
    R_USER_ID BIGINT,
    DESCRIPTION VARCHAR(255),
    CANCELLED BOOLEAN not null,
    VALIDATE VARCHAR(10) default 'INSERTED',
    STATUS VARCHAR(10),
    constraint FK3H0SO8JJDQDGNN9PY00I83OFU
        foreign key (R_ANNOUNCE_ID) references ANNOUNCE,
    constraint FKTCN6F6DKS6UF7KRCMVV2KHAU0
        foreign key (R_USER_ID) references USER
);

create table RESERVATION_CATEGORY
(
    RESERVATION_ID BIGINT not null,
    CATEGORIES_CODE VARCHAR(15) not null,
    primary key (RESERVATION_ID, CATEGORIES_CODE),
    constraint FKGCK7KFDQS1IFHMYB24PP251JL
        foreign key (RESERVATION_ID) references RESERVATION,
    constraint FKHI8HYAJ537D5OQOK2XA9UAIN1
        foreign key (CATEGORIES_CODE) references CATEGORY
);

create table REVIEW
(
    ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_DD8360C7_BF3E_4529_809B_C1286E35FFEE) auto_increment,
    DATECREATED TIMESTAMP(26,6),
    LASTUPDATED TIMESTAMP(26,6),
    TOKEN VARCHAR(5) not null,
    DETAILS VARCHAR(5000) not null,
    TITLE VARCHAR(35) not null,
    RATING INTEGER not null,
    CANCELLED BOOLEAN not null,
    INDEXES INTEGER not null,
    R_USER_ID BIGINT not null,
    RATING_USER_ID BIGINT,
    constraint FKMN7YQ16MASQJ4ODIT0TOHL3XS
        foreign key (R_USER_ID) references USER
);

create table SUBSCRIBERS
(
    R_USER_ID BIGINT not null,
    SUBSCRIBER_ID BIGINT not null,
    primary key (R_USER_ID, SUBSCRIBER_ID),
    constraint FK1NVJXHQAUIACV41MVBPO4R6IU
        foreign key (R_USER_ID) references USER,
    constraint FKOGEX3X8F6IE4WW40KGOI8O98U
        foreign key (SUBSCRIBER_ID) references USER
);

create table SUBSCRIPTIONS
(
    SUBSCRIPTION_ID BIGINT not null,
    R_USER_ID BIGINT not null,
    primary key (SUBSCRIPTION_ID, R_USER_ID),
    constraint FK5MGUIDOAT1GBMLUK1NV9VHJKD
        foreign key (R_USER_ID) references USER,
    constraint FKG9EHR2OF3WIDR0N9R03M5U6SA
        foreign key (SUBSCRIPTION_ID) references USER
);

create unique index PRIMARY_KEY_273
    on USER (ID);

create table USER_COMMUNICATION
(
    USERS_ID BIGINT not null,
    COMMUNICATIONS_ID BIGINT not null,
    primary key (USERS_ID, COMMUNICATIONS_ID),
    constraint FKAACENEGVR45D01M491GVVB7XE
        foreign key (USERS_ID) references USER,
    constraint FKPPG2OD2BISCSJQOY2F9EU0YHP
        foreign key (COMMUNICATIONS_ID) references COMMUNICATION
);

create table USER_NOTIFICATION
(
    USERS_ID BIGINT not null,
    NOTIFICATIONS_ID BIGINT not null,
    primary key (USERS_ID, NOTIFICATIONS_ID),
    constraint FK8HR3CBMBTB3NDL456F6BASWMN
        foreign key (NOTIFICATIONS_ID) references NOTIFICATION,
    constraint FKO1QX6Y02V6L3UXNG68RXJD9GR
        foreign key (USERS_ID) references USER
);

create table USER_ROLE
(
    R_USER BIGINT not null,
    ROLE_ID INTEGER not null,
    primary key (R_USER, ROLE_ID),
    constraint FKH3WNT7IJXYT7F1JS45H8W3FOH
        foreign key (R_USER) references USER,
    constraint FKN1RN9QODD3U4LE8UF3KL33QE3
        foreign key (ROLE_ID) references ROLE
);

