create schema VIEWS;

CREATE VIEW VIEWS.V_ANNOUNCES AS
  SELECT A1.*,U.USERNAME,M2.ID AS MSG_ID, M2.CONTENT, M2.R_USER_ID AS MSG_USER
  FROM ANNOUNCE A1
    LEFT JOIN MESSAGE M2 on A1.ID = M2.R_ANNOUNCE
    LEFT JOIN USER U on M2.R_USER_ID = U.ID;


SELECT USR.* FROM USER USR
LEFT JOIN ANNOUNCE A on USR.ID = A.R_USER_ID
LEFT JOIN MESSAGE M2 on A.ID = M2.R_ANNOUNCE
--LEFT JOIN MESSAGE M3 on M3.R_USER_ID = USR.ID
WHERE A.ANNOUNCE_TYPE='SELLER';

--UPDATE PUBLIC.ANNOUNCE U SET REMAIN_WEIGHT = (SELECT  WEIGHT FROM ANNOUNCE A WHERE U.ID = A.ID )

