CREATE SCHEMA VIEWS;

DROP VIEW VIEWS.RESERVATION_RECEIVED;
CREATE VIEW   VIEWS.RESERVATION_RECEIVED AS
SELECT R.ID AS RESERV_ID,
       R.WEIGTH,R.VALIDATE, A.DEPARTURE,
       A.ARRIVAL,A.START_DATE,A.END_DATE,
       U.ID AS USER_ID,U.USERNAME
FROM PUBLIC.RESERVATION R
INNER JOIN ANNOUNCE A ON A.ID = R.R_ANNOUNCE_ID
INNER JOIN USER U ON A.R_USER_ID = U.ID
WHERE  R.CANCELLED IS FALSE
AND A.CANCELLED IS FALSE
AND A.STATUS ='VALID';


DROP VIEW VIEWS.RESERVATION_CREATED;
CREATE VIEW VIEWS.RESERVATION_CREATED AS
SELECT R.ID AS RESERV_ID,
       R.WEIGTH,R.VALIDATE, A.DEPARTURE,
       A.ARRIVAL,A.START_DATE,A.END_DATE,
       U.ID AS USER_ID,U.USERNAME
FROM PUBLIC.RESERVATION R
         INNER JOIN ANNOUNCE A ON A.ID = R.R_ANNOUNCE_ID
         INNER JOIN USER U ON R.R_USER_ID = U.ID
WHERE  R.CANCELLED IS FALSE
  AND A.CANCELLED IS FALSE
  AND A.STATUS ='VALID';
